trigger:
  batch: true
  branches:
    include:
    - develop
    - main

variables:
  tag: '$(Build.BuildId)'

pool: 
  vmImage: 'ubuntu-latest'

steps:
  - task: Maven@3
    displayName: "Build project with maven"
    inputs:
      mavenPomFile: "pom.xml"
      mavenOptions: "-Xmx3072m"
      javaHomeOption: "path"
      jdkVersionOption: "1.11"
      jdkArchitectureOption: "x64"
      publishJUnitResults: true
      testResultsFiles: "**/surefire-reports/TEST-*.xml"
      goals: "deploy"
      options: "-Dgpg.skip=false"