trigger:
  batch: true
  branches:
    include:
    - develop
    - main

variables:
  tag: '$(Build.BuildId)'

pool: 
  vmImage: ''

steps:
  - task: DownloadSecureFile@1
    name: settingsxml
    displayName: Download maven settings xml
    inputs:
      secureFile: settings_min.xml
  - task: Maven@3
    displayName: "Build project with maven"
    inputs:
      mavenPomFile: "pom.xml"
      mavenOptions: "-Xmx3072m"
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.11"
      jdkArchitectureOption: "x64"
      publishJUnitResults: true
      testResultsFiles: "**/surefire-reports/TEST-*.xml"
      goals: "deploy"
      options: "-s $(settings_min.xml.secureFilePath) -Dgpg.skip=false"